### ISSUE TITLE
[SUGGESTION] Add Icon Legend Map

### ISSUE THREAD

**Issue by he7yz** [nattprog/fcimap#18]
**Reason**
For users who don't know what the icons symbolize @JC-stuff 
 (ex: the difference between orange icon with the "?", the blue navigation icon, and the red user icon).

![IconLegendList drawio](https://github.com/user-attachments/assets/e76e829e-fb0d-4d0a-87ed-5bfab7f5ed85)

**Comment by nattprog** [comment]
That's a great suggestion! We'll start work on it asap.
(the dedication to making an illustration tho T.T)

**Comment by he7yz** [comment]
lel thx =w=

**Comment by nattprog** [comment]
Website has been updated ^^

**Comment by he7yz** [comment]
thanks nat!!!! wowee

**Comment by he7yz** [comment]
AHHAAHHAHAHHA
![image](https://github.com/user-attachments/assets/e48e1c20-accc-4295-9b80-98acb9ff43fe)

**Comment by JC-stuff** [comment]
oc i have to wrote some bullshit to make more lines

**Comment by he7yz** [comment]
very poetic lol
